//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrn_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_222
    {
        public int id_table_22 { get; set; }
        public Nullable<int> car_god_proizvod { get; set; }
        public Nullable<int> car_id { get; set; }
    
        public virtual table_111 table_111 { get; set; }
    }
}
